### ISSUE TITLE
New version for nopCommerce 4.30?

### ISSUE THREAD

**Issue by jarijari** [Volki312/nopApplicationInsightsPlugin#5]
Dear Josip,

I would like to add Application Insights into our new nopCommerce webshop that's running on Azure Linux App service. I found these two very promising plugins from you and your very professional looking wiki page (unfortunately I can't understand it).

Nevertheless, I wanted to ask if these plugins are usable with 4.30 as well? Should I compile them myself - it seems that you do not provide releases, right?

Thanks!

Kind regards
Jari Kirvesoja

**Comment by Volki312** [comment]
Hello Jari,I will look into your email tonight once I find some time! :)Kind regards,Josip VolarevićSent from my Samsung Galaxy smartphone.
-------- Original message --------From: jarijari <notifications@github.com> Date: 6/16/20  23:26  (GMT+01:00) To: Volki312/nopApplicationInsightsPlugin <nopApplicationInsightsPlugin@noreply.github.com> Cc: Subscribed <subscribed@noreply.github.com> Subject: [Volki312/nopApplicationInsightsPlugin] New version for nopCommerce 4.30? (#5) 
Dear Josip,
I would like to add Application Insights into our new nopCommerce webshop that's running on Azure Linux App service. I found these two very promising plugins from you and your very professional looking wiki page (unfortunately I can't understand it).
Nevertheless, I wanted to ask if these plugins are usable with 4.30 as well? Should I compile them myself - it seems that you do not provide releases, right?
Thanks!
Kind regards
Jari Kirvesoja

—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/Volki312/nopApplicationInsightsPlugin/issues/5",
"url": "https://github.com/Volki312/nopApplicationInsightsPlugin/issues/5",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by Volki312** [comment]
Hi jarijari,This was a project I did for my internship, I have used it as an opportunity to learn C#, ASP.NET core, nopCommerce etc.I think the plugin should work the same on 4.30 version of nopCommerce, maybe with some minor tweaks? You should compile the code and check by yourself to know for sure. The documentation is sadly on Croatian, as I had to submit the internship task on that language.The plugin and theme have a few issues or need some fixes. I'd suggest starting your own AI integration plugin and following my source code along the way as a guideline, or forking my repos and improving the code.I don't have enough free time to explain the AI plugin and theme project to you, so sorry about that. Wish you luck and hope my code helps you in some way at least! :)Kind regards,JosipSent from my Samsung Galaxy smartphone.
-------- Original message --------From: jarijari <notifications@github.com> Date: 6/16/20  23:26  (GMT+01:00) To: Volki312/nopApplicationInsightsPlugin <nopApplicationInsightsPlugin@noreply.github.com> Cc: Subscribed <subscribed@noreply.github.com> Subject: [Volki312/nopApplicationInsightsPlugin] New version for nopCommerce 4.30? (#5) 
Dear Josip,
I would like to add Application Insights into our new nopCommerce webshop that's running on Azure Linux App service. I found these two very promising plugins from you and your very professional looking wiki page (unfortunately I can't understand it).
Nevertheless, I wanted to ask if these plugins are usable with 4.30 as well? Should I compile them myself - it seems that you do not provide releases, right?
Thanks!
Kind regards
Jari Kirvesoja

—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/Volki312/nopApplicationInsightsPlugin/issues/5",
"url": "https://github.com/Volki312/nopApplicationInsightsPlugin/issues/5",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by jarijari** [comment]
Hi Josip,

thanks a lot for your quick response! Ok, I'll look at forking your code when I have better time.

Cheers,
Jari
